name: choreo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - matplotlib
  - scipy
  - networkx
  - cython
  - ffmpeg
  - suitesparse
  - ffmpeg-python
  - tbb-devel
  - mkl-devel
  - pip
  - pip:
    - cffi==1.15.0
    - pycparser==2.21
    - sparseqr==1.1.2
