name: choreo
channels:
  - conda-forge
dependencies:
  - python=3.12.1
  - mpmath
  - matplotlib
  - scipy
  - networkx
  - cython
  - ffmpeg
  - fftw
  - tbb 
  - ffmpeg-python
  - pip
  - mkl_fft
  - pyamg
  - numba
  - pytest
  - pytest-xdist
  - attrs
  - pyodide-build
  - Sphinx
  - pydata-sphinx-theme
  - sphinx-gallery
  - sphinx-needs
  - pyquickbench
  - threadpoolctl
  - pip:
    - sphinx-pyproject
    - sphinx-test-reports
    - sphinxcontrib.plantuml
    - pyfftw@git+https://github.com/pyFFTW/pyFFTW.git@92879c332e03e07ce111e817798663c34dddb42e  