name: choreo
channels:
  - conda-forge
  - defaults
  - numba
dependencies:
  - python=3.10
  - mpmath
  - matplotlib
  - scipy
  - networkx
  - cython
  - ffmpeg
  - suitesparse
  - tbb 
  - ffmpeg-python
  - pip
  - mkl
  - mkl_fft
  - pyamg
  - numba
  - icc_rt
  - pip:
    - cffi==1.15.0
    - pycparser==2.21
    - sparseqr==1.1.2
