name: choreo-new
channels:
  - conda-forge
dependencies:
  - build
  - python=3.12.1
  # - pyodide-build=0.26.0
  - mpmath
  - matplotlib
  - scipy
  - networkx
  - cython
  - ffmpeg
  - suitesparse
  - tbb 
  - ffmpeg-python
  - pip
  - numba
  - pytest
  - pytest-xdist
  - attrs
  - threadpoolctl
  - pip:
    - pyodide-build==0.26.0
    - cffi==1.15.0
    - pycparser==2.21
    - sparseqr==1.1.2