[build-system]
requires = [
    "setuptools"    ,   
    "wheel"         ,
    "cython"        ,
    "numpy"         ,
    "matplotlib"    ,
    "scipy"         ,
    "networkx"      ,
    "ffmpeg"        ,
    "ffmpeg-python" ,
    "cffi"          ,
    "pycparser"     ,
    "sparseqr"      ,
    ]
build-backend = "setuptools.build_meta"