[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "Cython",
    "numpy",
    "scipy",
    "build",
]
build-backend = "setuptools.build_meta"

[project]
name = "choreo"  # as it would appear on PyPI
version = "0.2.0"
description = "A set of tools to compute periodic solutions to the Newtonian N-body problem"
readme = {file = "README.md", content-type = "text/markdown"}
license = {file = "LICENSE"}
keywords = ["ODE","periodic","N-body","gravitation"]
authors = [
  {name = "Gabriel Fougeron", email = "gabriel.fougeron@hotmail.fr"},
]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Programming Language :: Python :: 3",
  "Programming Language :: Cython",
  "Programming Language :: JavaScript",
  "Environment :: WebAssembly :: Emscripten",
  "Intended Audience :: Education",
  "License :: OSI Approved :: BSD License",
  "Natural Language :: English",
  "Topic :: Scientific/Engineering :: Mathematics",
  "Topic :: Scientific/Engineering :: Physics",
]
requires-python = ">= 3.9"
dependencies = [
  "scipy",
  "numpy",
  "matplotlib",
  "sparseqr==1.2",
  "networkx",
  "mpmath",
]

[project.optional-dependencies]
gui = [
  "pyodide-build==0.23.4",
]
cli = [
  "numba",
]
docs = [
  "Sphinx==5.1.1",
  "sphinx-rtd-theme==1.0.0",
  "sphinx-gallery==0.11.1",
]

[project.scripts]
choreo_GUI_in_CLI = "choreo.Choreo_run:entrypoint_GUI_in_CLI"

[project.urls]
Homepage = "https://gabrielfougeron.github.io/choreo/"
Documentation = "https://gabrielfougeron.github.io/choreo-docs/"
Repository = "https://github.com/gabrielfougeron/choreo"
Changelog = "https://github.com/gabrielfougeron/choreo/releases/"


