[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "Cython",
    "numpy",
    "scipy",
    "build",
]
build-backend = "setuptools.build_meta"

[project]
name = "choreo"  # as it would appear on PyPI
version = "0.2.0"
description = "A set of tools to compute periodic solutions to the Newtonian N-body problem"
readme = {file = "README.md", content-type = "text/markdown"}
license = {file = "LICENSE"}
keywords = ["ODE","periodic","N-body","gravitation"]
authors = [
  {name = "Gabriel Fougeron", email = "gabriel.fougeron@hotmail.fr"},
]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Programming Language :: Python :: 3",
  "Programming Language :: Cython",
  "Programming Language :: JavaScript",
  "Environment :: WebAssembly :: Emscripten",
  "Intended Audience :: Education",
  "License :: OSI Approved :: BSD License",
  "Natural Language :: English",
  "Topic :: Scientific/Engineering :: Mathematics",
  "Topic :: Scientific/Engineering :: Physics",
]
requires-python = ">= 3.9"
dependencies = [
  "scipy",
  "numpy",
  "matplotlib",
  "sparseqr==1.2",
  "networkx",
  "mpmath",
]

[project.optional-dependencies]
gui = [
  "pyodide-build==0.23.4",
]
cli = [
  "numba",
]
unittest = [
  "choreo[cli]",
  "attrs",
  "pytest",
  "pytest-xdist",
  "pytest-cov",
  "pytest-cython",
  "pytest-envfiles",
]
regtest = [
  "tox",
  "tox-gh-actions",
]
docs = [
  "choreo[test]",
  "Sphinx",
  "pydata-sphinx-theme",
  "sphinx-gallery",
  "sphinx-pyproject",
  "sphinx-needs",
  "sphinx-test-reports",
  "sphinxcontrib.plantuml",
]
full = [
  "choreo[gui,cli,docs,unittest,regtest]"
]

[project.scripts]
choreo_GUI_in_CLI = "choreo.Choreo_run:entrypoint_GUI_in_CLI"

[project.urls]
Homepage = "https://gabrielfougeron.github.io/choreo/"
Documentation = "https://gabrielfougeron.github.io/choreo-docs/"
Repository = "https://github.com/gabrielfougeron/choreo"
Changelog = "https://github.com/gabrielfougeron/choreo/releases/"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-v -ra --junit-xml=docs/pytest_out/junit.xml"
testpaths = [
    "tests",
]
filterwarnings = [
    "ignore::DeprecationWarning",
]
junit_family = "xunit2"
junit_logging = "system-out"
junit_suite_name = "Pytest test results"
junit_log_passing_tests = true

[tool.tox]
legacy_tox_ini = """
[tox]
min_version = 4.0
env_list =
    py{39,310,311}

[gh-actions]
python = 
    3.9: py39
    3.10: py310
    3.11: py311

[testenv]
extras = docs
commands = 
      pytest 
      sphinx-build -d "{envtmpdir}{/}doctree" docs/source "{toxworkdir}{/}docs_out" --color -b html
"""

