name: Tox regression tests

on: workflow_dispatch 

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    # 
    - name: Checkout repository
      uses: actions/checkout@v3
    # 
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    #
    - name: Install apt-get dependencies for Ubuntu
      run: |
        sudo apt-get update
        sudo apt-get install libsuitesparse-dev
        sudo apt-get install plantuml
    #
    - name: Install python build dependencies
      run: |
        pip install --upgrade pip
        pip install .[full]
    - name: Run regression tests
      run: |
        tox
