name: Unit tests on diverse OS

on: workflow_dispatch 

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        # python-version: ["3.9", "3.10", "3.11"]
        python-version: ["3.11"]
        # os: [ubuntu-22.04, ubuntu-20.04, macos-latest, windows-latest]
        os: [ubuntu-latest, macos-latest, windows-latest]
    #
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
    # 
    - name: Checkout repository
      uses: actions/checkout@v3
    # 
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}
        conda-channels: anaconda, conda-forge
    #
    - name: Install common dependencies
      run: |
        conda install -c conda-forge -y suitesparse clang plantuml openmp
    - name: Install dependencies for MacOs
      if: startsWith(matrix.os, 'macos')
      run: |        
        sudo rm -rf /Library/Developer/CommandLineTools
        xcode-select --install
    #
    - name: Install dependencies for Windows
      if: startsWith(matrix.os, 'windows')
      run: |
        cd "C:\Miniconda\envs\__setup_conda\Library\include\"
        dir
        $env:Path += ';C:\Miniconda\envs\__setup_conda\Library\include\suitesparse' 
    # # 
    - name: Install python build dependencies
      run: |
        pip install --upgrade pip
        pip install .[cli,docs,test,build]
    #
    - name: Run tests
      run: |
        pytest
    #
    - name: Generate Documentation
      run: |
        python setup.py build_ext --inplace
        cd docs
        make html
