name: Unit tests on diverse OS

on: workflow_dispatch 

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        os: [ubuntu-22.04, ubuntu-20.04, macos-13, macos-12, macos-11]
    #
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
    # 
    - name: Checkout repository
      uses: actions/checkout@v3
    # 
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    #
    - uses: ConorMacBride/install-package@main
      with:
        brew: libomp-dev libsuitesparse-dev plantuml
        apt: libomp-dev libsuitesparse-dev plantuml build-essential
        choco: libomp-dev libsuitesparse-dev plantuml
    # - name: Install apt-get dependencies for Ubuntu
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install libomp-dev libsuitesparse-dev
    #     sudo apt-get install plantuml
    # No GUI here since pyodide only supports one version on python at a time
    - name: Install python build dependencies
      run: |
        pip install --upgrade pip
        pip install .[cli,docs,test]
    #
    - name: Run tests
      run: |
        pytest
    #
    - name: Generate Documentation
      run: |
        python setup.py build_ext --inplace
        cd docs
        make html
