name: Unit tests on diverse OS

on: workflow_dispatch 

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        os: [ubuntu-22.04, ubuntu-20.04, macos-latest, windows-latest]
    #
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
    # 
    - name: Checkout repository
      uses: actions/checkout@v3
    # 
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}
        conda-channels: anaconda, conda-forge
    #
    - name: Install dependencies for Ubuntu
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        conda install -y suitesparse clang plantuml
    #
    - name: Install dependencies for MacOs
      if: startsWith(matrix.os, 'macos')
      run: |
        conda install -y suitesparse clang plantuml
    #
    - name: Install choco dependencies for Windows
      if: startsWith(matrix.os, 'windows')
      run: |
        conda install -y suitesparse clang plantuml
    # 
    - name: Install python build dependencies
      run: |
        pip install --upgrade pip
        pip install .[cli,docs,test,build]
    #
    - name: Run tests
      run: |
        pytest
    #
    - name: Generate Documentation
      run: |
        python setup.py build_ext --inplace
        cd docs
        make html
