name: Unit tests on diverse OS

on: workflow_dispatch 

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        os: [ubuntu-22.04, ubuntu-20.04, macos-13, macos-12, macos-11]
    #
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
    # 
    - name: Checkout repository
      uses: actions/checkout@v3
    # 
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    #
    - name: Install apt-get dependencies for Ubuntu
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get install libomp-dev libsuitesparse-dev clang
        sudo apt-get install plantuml
    #
    - name: Install brew dependencies for MacOs
      if: startsWith(matrix.os, 'macos')
      run: |
        brew update
        brew upgrade
        brew install libomp suite-sparse plantuml
    # 
    - name: Install python build dependencies
      run: |
        pip install --upgrade pip
        pip install .[cli,docs,test,build]
    #
    - name: Run tests
      run: |
        pytest
    #
    - name: Generate Documentation
      run: |
        python setup.py build_ext --inplace
        cd docs
        make html
